version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - chore

  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - chore
